openapi: "3.0.0"
info:
  title: TEST API
  description: Locahost api to test OpenAPI swagger
  version: '1.0'
servers:
  - url: http://localhost:3000/api
    description: Locahost server
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Get users
      responses:
        '200':
          description: A JSON array of users and their data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
